language: php

php:
  - 7.4
  - 7.3
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit

